### ISSUE TITLE
USER STORY: View Posts

### ISSUE THREAD

**Issue by helenmurugan** [helenmurugan/the-groomers-network#1]
As a **Site User**, I can **view a list of posts** so that **I can click on a post to view the full content**

Acceptance Criteria

- All posts can be viewed by authorised users
- Users can select from a list of posts to view a particular post in detail
- Post titles can be clicked on to view the post in more detail

Tasks

- [x] Add Posts model
- [x] Add views to display post list and post detail
- [x] Add templates to render post views
- [x] Add style to post templates
