### ISSUE TITLE
USER STORY: Site management

### ISSUE THREAD

**Issue by helenmurugan** [helenmurugan/the-groomers-network#16]
As a **Site Admin**, I can **use a dedicated admin panel** so that **I can delete any inappropriate content and manage the content of the site**

Acceptance Criteria:

- Site admin can log in to admin panel
- Site admin can create, read, update and delete posts and comments
- Site admin can view a list of registered users and delete if necessary
- Site admin can filter posts and comments by created on date
- Site admin can use search function to locate a specific post, comment or profile

Tasks:

- [x] Implement an admin dashboard
- [x] Customise posts section that can be managed by admin
- [x] Customise comments section that can be managed by admin
- [x] Customise events section that can be managed by admin
- [x] Customise profiles section that can be managed by admin
