### ISSUE TITLE
USER STORY: View Events

### ISSUE THREAD

**Issue by helenmurugan** [helenmurugan/the-groomers-network#19]
As a **Site User**, I can **view a list of events and click on an event** so that **I can read the full content**

Acceptance Criteria

- Events can be added by admin only
- Users can select from a list of events to view a particular event

Tasks

- [x] Add Events model
- [x] Add view to display Events
- [x] Add template to render Events list and Events detail views
- [x] Add style to events templates
