### ISSUE TITLE
USER STORY: Interact using comments

### ISSUE THREAD

**Issue by helenmurugan** [helenmurugan/the-groomers-network#20]
As a **Site User**, I can **manage my comments on posts** so that **I can be a part of the conversation**

Acceptance Criteria

- Users can comment on posts
- Users can view all comments on the post
- Users can delete their own posts
- On deletion of a comment, user should have the option to confirm or cancel the deletion.
- User should be redirected to relevant post after cancelling deletion of a comment
- User should be redirected to relevant post after deletion of a comment.

Tasks

- [x] Add Comments model
- [x] Add View to display Comments so that the conversation can be read.
- [x] Use Django's DeleteView to create delete functionality for comments
- [x] Add form with validation to handle comments
- [x] Add style to comments
