### ISSUE TITLE
USER STORY: User profile

### ISSUE THREAD

**Issue by helenmurugan** [helenmurugan/the-groomers-network#25]
As a **Site User**, I can **manage my profile** so that **I can display and update my details as necessary**

Acceptance Criteria:

- An empty user profile is created automatically on registration of a new user
- Users can read and update their profile
- Users can easily navigate to their profile from the navbar

Tasks:

- [x] Create model for user profile.
- [x] Add new user profile using signalling.
- [x] Add view to edit user profile.
- [x] Create template for viewing my profile.
- [x] Create crispy form for updating my profile.
