### ISSUE TITLE
USER STORY: Like/Unlike Events

### ISSUE THREAD

**Issue by helenmurugan** [helenmurugan/the-groomers-network#3]
As a **Site User**, I can **like or unlike an event** so that **I can interact with the content**

Acceptance Criteria:

- Users can toggle like/unlike by clicking
- Users can view the number of likes on an event
- Users can immediately see if they have liked an event

Tasks
- [x] Add Font Awesome icons to demonstrate likes
- [x] Add view to like/unlike events
- [x] Add view for the number of likes on an event
- [x] Add the number of likes to the Event list and Event detail templates.
