### ISSUE TITLE
USER STORY: Images

### ISSUE THREAD

**Issue by helenmurugan** [helenmurugan/the-groomers-network#30]
As a **Site User**, I can **upload and view images** so that **posts are meaningful and engaging**

Acceptance Criteria

- Users can upload images together with the content of their posts
- Users can view images uploaded by other users/admin
- When a user does not upload an image, a placeholder image should be used.

Tasks

- [x] Add functionality to upload images
- [x] Add functionality to view images
- [x] Add placeholder image
