### ISSUE TITLE
USER STORY: Like/Unlike Posts

### ISSUE THREAD

**Issue by helenmurugan** [helenmurugan/the-groomers-network#7]
As a **Site User**, I can **like or unlike a post** so that **I can interact with the content**

Acceptance Criteria:

- Users can toggle like/unlike by clicking on heart icon
- Users can see immediately if they have liked a post.
- Users can view the number of likes on a post

Tasks
- [x] Add Font Awesome icons to demonstrate likes
- [x] Add view to like/unlike posts
- [x] Add view to display number of likes
- [x] Add number of likes to post list and post detail pages
