### ISSUE TITLE
USER STORY: Create and Manage Posts

### ISSUE THREAD

**Issue by helenmurugan** [helenmurugan/the-groomers-network#8]
As a **Site User**, I can **create and manage my own posts** so that **I can network with other users**

Acceptance Criteria

- Users can create posts
- Users can select any post to view
- User can update their own posts
- Users can delete their own posts
- Users should be shown a confirmation page before deleting a post, where they have the option to Cancel or Confirm.
- On deletion of a post, users should be redirected to posts page.
- On cancelling post deletion, users should be redirected back to the post detail view.

Tasks

- [x] Add Post model
- [x] Use Django's CreateView to add create functionality
- [x] Use Django's UpdateView to add update functionality
- [x] Add Crispy form with validation for Create and Update pages
- [x] Use Django's DeleteView to add delete functionality
- [x] Add templates to view a list of posts and individual posts
- [x] Style templates
